import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { Be_Vietnam_Pro } from "next/font/google";

const beVietam = Be_Vietnam_Pro({ subsets: ["latin"], weight: ['400', '600', '700']  });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={beVietam.className}>
      <Header />
      {children}
      </body>
    </html>
  );
}
